# Autogenerated, do not edit. All changes will be undone.
# Source: https://github.com/pls-rs/pls/blob/main/pkg/brew/pls.template
class Pls < Formula
  desc "Prettier and powerful ls for the pros"
  homepage "https://pls.cli.rs/"
  version "0.0.1-beta.8"
  license "GPL-3.0-or-later"

  if OS.mac?
    url "https://github.com/pls-rs/pls/releases/download/v0.0.1-beta.8/pls-x86_64-apple-darwin.zip"
    sha256 "3ad5628a70fd1ebe3ca933edd4dd59c9bcbf158aabb3e8aa671428068db9981d"
  elsif OS.linux?
    url "https://github.com/pls-rs/pls/releases/download/v0.0.1-beta.8/pls-x86_64-unknown-linux-musl.zip"
    sha256 "636d7b96c25b9d74fbb6a863fbf045e1db6501b83e14865134e794789a780961"
  end

  depends_on "libgit2"

  def install
    bin.install "pls"
  end

  test do
    linkage_with_libgit2 = (bin/"pls").dynamically_linked_libraries.any? do |dll|
      next false unless dll.start_with?(HOMEBREW_PREFIX.to_s)

      File.realpath(dll) == (Formula["libgit2"].opt_lib/shared_library("libgit2")).realpath.to_s
    end

    assert linkage_with_libgit2, "No linkage with libgit2! Cargo is likely using a vendored version."
  end
end
