# Autogenerated, do not edit. All changes will be undone.
# Source: https://github.com/pls-rs/pls/blob/main/pkg/brew/pls.template
class Pls < Formula
  desc "Prettier and powerful ls for the pros"
  homepage "https://pls.cli.rs/"
  version "0.0.1-beta.9"
  license "GPL-3.0-or-later"

  if OS.mac?
    url "https://github.com/pls-rs/pls/releases/download/v0.0.1-beta.9/pls-x86_64-apple-darwin.zip"
    sha256 "0a0909e27cb4eb44fbc78f3f0ec801f1c4954dfd41e94a5538155ac8aba27427"
  elsif OS.linux?
    url "https://github.com/pls-rs/pls/releases/download/v0.0.1-beta.9/pls-x86_64-unknown-linux-musl.zip"
    sha256 "56d29ff2c0d918c794f8bd248471e8244891d366f1cf0886b8111f59a7a31a82"
  end

  depends_on "libgit2"

  def install
    bin.install "pls"
  end

  test do
    linkage_with_libgit2 = (bin/"pls").dynamically_linked_libraries.any? do |dll|
      next false unless dll.start_with?(HOMEBREW_PREFIX.to_s)

      File.realpath(dll) == (Formula["libgit2"].opt_lib/shared_library("libgit2")).realpath.to_s
    end

    assert linkage_with_libgit2, "No linkage with libgit2! Cargo is likely using a vendored version."
  end
end
