name: Lint

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  tap-syntax:
    runs-on: ubuntu-latest
    container: ghcr.io/homebrew/brew:main
    permissions:
      contents: read
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: brew test-bot --only-tap-syntax
